service: playground-gcmae-dynamodb

provider:
  name: aws
  runtime: nodejs4.3

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
      Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.stage}-*"

custom:
  defaultStage: dev
  defaultRegion: ap-northeast-1

functions:
  todosReadAll:
    handler: handler.todosReadAll
    events:
      - http:
          path: todos
          method: get
          cors: true
  todosUpdate:
    handler: handler.todosUpdate
    events:
      - http:
          path: todos/update
          method: post
          cors: true
resources:
  Resources:
    TodosDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: issues
            AttributeType: S
        KeySchema:
          -
            AttributeName: issues
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: "playground-gcmae"
